replicaCount: 1

image:
  repository: akshay2001a/nodejs-app
<<<<<<< HEAD
  tag: "10"
  pullPolicy: IfNotPresent
=======
  tag: "10"
  pullPolicy: Always
>>>>>>> 31049db (value.yaml configured)

service:
  type: NodePort
  port: 80
  nodePort: 30007

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: nodejs-app.local
      paths: ["/"]
  tls: []

resources: {}
